# Generated by Django 3.0.8 on 2020-11-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleTask',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('playbook_id', models.IntegerField()),
                ('playbook_name', models.CharField(max_length=250)),
                ('hosts_group_id', models.IntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(default='queued', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=250)),
            ],
        ),
    ]
