# Generated by Django 3.0.8 on 2020-11-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletask',
            name='playbook_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
