version: "3.7"
   
services:
  cfg-mgnt:
    build: ./service-cfg-mgnt
    volumes:
      - ./service-cfg-mgnt:/code
    ports:
      - "9000:8000"

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    
  frontend:
    build: ./frontend
    expose:
      - 80
    volumes:
      - ./frontend:/frontend
    ports:
      - "80:80"