version: "3.3"
   
services:
  web:
    build: .
    command: bash -c "apt-get update
        && apt-get install sshpass
        && pip install junos-eznc
        && ansible-galaxy collection install juniper.device
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"