version: "3.3"
   
services:
  web:
    build: .
    command: bash -c "apt-get update
        && apt-get install sshpass
        && mkdir -p /etc/ansible
        && cp ansible_app/ansible_store/ansible.cfg /etc/ansible/ansible.cfg
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"