use Rex -feature => ['1.4'];

user 'user';
password 'password';
pass_auth;
sudo TRUE;
sudo_password 'password';

group testing => '192.168.0.3';

desc 'Change hostname to anotherUser';
task 'hostname',
	group => 'testing',
	sub {
		sudo sub {
			run 'hostname anotherUser';
			my $output = run 'hostname';
			say $output;
		};
	};

desc 'Get hostname';
task 'getHostname',
	group => 'testing',
	sub {
		my $output = run 'hostname';
		say $output;
	};
